import type {
  PortfolioProject,
  ProjectShowcaseComponent,
} from "@/constants/types"

export const portfolioProjects: PortfolioProject[] = [
  {
    type: "project",
    slug: "codescope-ai",
    title: "CodeScope AI",
    col: 1,
    order: 1,
    media: [
      { type: "placeholder", alt: "CodeScope AI overview" },
    ],
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "AI Integration",
    ],
    description:
      "An AI-powered code analysis tool that scans repositories and provides insights on code quality, structure, and potential improvements. Built to help developers understand codebases faster through automated analysis.",
    challenges: [
      "Handling large `codebase scans` without blocking the UI or degrading response times.",
      "Presenting `AI-generated insights` in a scannable, developer-friendly format without overwhelming the interface.",
      "Managing `file tree navigation` alongside analysis results while keeping context across multiple files.",
    ],
    solutions: [
      "Implemented streaming responses with progressive `result rendering` to keep the interface responsive during analysis.",
      "Structured insights into categorized `analysis cards` with syntax highlighting, file references, and severity levels.",
      "Built a `split-pane layout` with synchronized file tree and detail view using shared state management.",
    ],
  },
  {
    type: "project",
    slug: "study-runtime",
    title: "Study Runtime",
    col: 2,
    order: 1,
    media: [
      { type: "placeholder", alt: "Study Runtime overview" },
    ],
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "MongoDB",
      "Prisma",
    ],
    description:
      "A study planning and session management application that helps students organize their study schedule, track session progress, and maintain consistent study habits through structured runtime tracking.",
    challenges: [
      "Building a `session timer` that accurately tracks study time across browser tabs without losing state on navigation.",
      "Designing a `planning interface` that supports flexible scheduling without becoming visually cluttered.",
      "Persisting `session history` and progress data reliably across devices and sessions.",
    ],
    solutions: [
      "Used `Web Workers` and localStorage fallback to maintain timer accuracy across tab switches and page reloads.",
      "Created a `drag-and-drop schedule builder` with collapsible day views and inline editing.",
      "Implemented `Prisma + MongoDB` with optimistic updates for real-time progress syncing.",
    ],
  },
  {
    type: "project",
    slug: "gitscope",
    title: "GitScope",
    col: 1,
    order: 2,
    media: [
      { type: "placeholder", alt: "GitScope overview" },
    ],
    stack: [
      "React",
      "TypeScript",
      "GitHub API",
      "Tailwind CSS",
    ],
    description:
      "A GitHub repository analytics tool that visualizes contribution patterns, code frequency, and repository health metrics. Designed to give developers a quick overview of any public repository's activity and structure.",
    challenges: [
      "Aggregating `GitHub API data` across multiple endpoints without hitting rate limits or causing excessive loading states.",
      "Visualizing `contribution data` in meaningful charts that convey trends without requiring interpretation.",
      "Handling `repository metadata` for large repos with extensive commit histories efficiently.",
    ],
    solutions: [
      "Implemented `request batching` and caching layers to minimize API calls while keeping data fresh.",
      "Built `interactive charts` with tooltips and time-range selectors for contribution and code frequency views.",
      "Used `pagination` and lazy loading for commit history and file tree data to maintain performance.",
    ],
  },
  {
    type: "project",
    slug: "ascii-studio",
    title: "ASCII Studio",
    col: 2,
    order: 2,
    media: [
      { type: "placeholder", alt: "ASCII Studio overview" },
    ],
    stack: [
      "React",
      "TypeScript",
      "Canvas API",
      "Tailwind CSS",
    ],
    description:
      "A browser-based tool that converts images into ASCII art with customizable character sets, resolution settings, and export options. Built for creative exploration of character-based image representation.",
    challenges: [
      "Processing `image data` into ASCII characters in real-time without blocking the main thread.",
      "Providing `live preview` updates as users adjust resolution, character density, and contrast settings.",
      "Supporting `export formats` that preserve the ASCII layout for sharing and embedding.",
    ],
    solutions: [
      "Offloaded `pixel analysis` to a Web Worker to keep the UI responsive during conversion.",
      "Implemented `debounced updates` with canvas-based rendering for smooth live preview.",
      "Added `text and PNG export` with configurable dimensions and character spacing.",
    ],
  },
  {
    type: "project",
    slug: "cube-timer",
    title: "Cube Timer",
    col: 1,
    order: 3,
    media: [
      { type: "placeholder", alt: "Cube Timer overview" },
    ],
    stack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
    ],
    description:
      "A Rubik's cube solving timer with session tracking, solve history, and statistical analysis. Supports multiple timing methods and provides insights into solve time distribution and improvement trends.",
    challenges: [
      "Achieving `millisecond-accurate timing` that responds instantly to keyboard and touch input.",
      "Displaying `session statistics` that update in real-time as new solves are recorded.",
      "Managing `solve history` with consistent formatting across sessions.",
    ],
    solutions: [
      "Used `high-resolution timestamps` with requestAnimationFrame for frame-accurate timing.",
      "Built a `live stats panel` with mean, best, and session averages that recalculate on each solve.",
      "Implemented `localStorage persistence` with structured session objects for reliable history tracking.",
    ],
  },
  {
    type: "project",
    slug: "netflix-clone",
    title: "Netflix Clone",
    col: 2,
    order: 3,
    media: [
      { type: "placeholder", alt: "Netflix Clone overview" },
    ],
    stack: [
      "React",
      "TypeScript",
      "TMDB API",
      "Tailwind CSS",
      "Framer Motion",
    ],
    description:
      "A front-end recreation of Netflix's browsing interface using the TMDB API for movie and TV show data. Implements the horizontal scroll carousel layout, search functionality, and responsive video preview interactions.",
    challenges: [
      "Replicating the `horizontal carousel` scroll behavior with smooth momentum and peek preview.",
      "Building a `search interface` that provides instant results without excessive API requests.",
      "Matching the `responsive layout` across desktop, tablet, and mobile viewports.",
    ],
    solutions: [
      "Implemented `CSS scroll snap` with JavaScript-enhanced navigation for smooth carousel scrolling.",
      "Added `debounced search` with result caching and skeleton loading states.",
      "Used `responsive grid` and breakpoint-aware component rendering for consistent cross-device layout.",
    ],
  },
]

export const portfolioShowcaseComponents: ProjectShowcaseComponent[] = [
  {
    type: "showcase",
    title: "Edit Time",
    stack: ["motion", "typescript"],
    media: {
      type: "video",
      src: "https://pub-17f1ae3c481641228230d1b2dcdc07ff.r2.dev/craft/iIFMesf2PYlUOc28.mp4",
      width: 2338,
      height: 832,
      alt: "Edit Time interaction preview",
    },
    col: 1,
    order: 8,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Card Hover",
    stack: ["motion", "react"],
    media: {
      type: "component",
      componentKey: "card-hover",
      alt: "Interactive holographic card hover component",
    },
    col: 1,
    order: 4,
    xLink: "",
  },
  {
    type: "showcase",
    title: "GLSL Shader Fragment",
    stack: ["glsl", "motion"],
    media: {
      type: "video",
      src: "https://pub-17f1ae3c481641228230d1b2dcdc07ff.r2.dev/craft/Shopify%20Transition.mp4",
      width: 1632,
      height: 1080,
      alt: "GLSL Shader Fragment",
    },
    col: 2,
    order: 4,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Gradient Slider Toggle",
    stack: ["motion", "typescript"],
    media: {
      type: "video",
      src: "https://pub-17f1ae3c481641228230d1b2dcdc07ff.r2.dev/craft/slider-gradient-1769668815641.mp4",
      width: 1624,
      height: 1080,
      alt: "Gradient Slider Toggle",
    },
    col: 1,
    order: 11,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Threejs Face Masking shader",
    stack: ["three.js", "shader"],
    media: {
      type: "video",
      src: "https://pub-17f1ae3c481641228230d1b2dcdc07ff.r2.dev/craft/lando-norris.mp4",
      width: 1080,
      height: 1616,
      alt: "Threejs Face Masking shader",
    },
    col: 2,
    order: 10,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Image Slider",
    stack: ["motion", "typescript"],
    media: {
      type: "video",
      src: "https://pub-17f1ae3c481641228230d1b2dcdc07ff.r2.dev/craft/vertical-slider-1765799424856.mp4",
      width: 1856,
      height: 1080,
      alt: "image slider",
    },
    col: 1,
    order: 10,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Subscriptions List",
    stack: ["motion", "typescript"],
    media: {
      type: "component",
      componentKey: "subscription",
      alt: "subscriptions list",
    },
    col: 2,
    order: 7,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Text to Bento cards",
    stack: ["motion", "typescript"],
    media: {
      type: "video",
      src: "https://pub-17f1ae3c481641228230d1b2dcdc07ff.r2.dev/craft/Recording%20at%202026-05-26%2017.26.39-Edited.mp4",
      width: 1662,
      height: 1080,
      alt: "text to bento cards",
    },
    col: 2,
    order: 4,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Liquid Glass Blob",
    stack: [""],
    media: {
      type: "component",
      componentKey: "liquid-glass-blob",
      alt: "liquid glass blob",
    },
    col: 1,
    order: 13,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Paper shred Button",
    stack: [""],
    media: {
      type: "component",
      componentKey: "paper-shred",
      alt: "paper shred button",
    },
    col: 2,
    order: 8,
    xLink: "",
    resettable: true,
  },
  {
    type: "showcase",
    title: "Analog Stick",
    stack: [""],
    media: {
      type: "component",
      componentKey: "analog-stick",
      alt: "analog stick",
    },
    col: 1,
    order: 6,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Polaroid stack",
    stack: [""],
    media: {
      type: "component",
      componentKey: "polaroid-stack",
      alt: "polaroid stack",
    },
    col: 2,
    order: 2,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Scan document interaction",
    stack: [""],
    media: {
      type: "component",
      componentKey: "scan-document",
      alt: "scan document button",
    },
    col: 2,
    order: 6,
    xLink: "",
    resettable: true,
  },
  {
    type: "showcase",
    title: "Theme Toggle",
    stack: [""],
    media: {
      type: "component",
      componentKey: "theme-toggle",
      alt: "theme toggle",
    },
    col: 1,
    order: 1,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Set timer interaction",
    stack: [""],
    media: {
      type: "component",
      componentKey: "set-timer",
      alt: "set timer interaction",
    },
    col: 1,
    order: 9,
    resettable: true,
    xLink: "",
  },
  {
    type: "showcase",
    title: "Timezone Showcase",
    stack: [""],
    media: {
      type: "component",
      componentKey: "timezone",
      alt: "timezone showcase",
    },
    col: 1,
    order: 7,
    xLink: "",
  },
]
